In [28]:
import numpy as np
import pandas as pd

In [29]:
df = pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [30]:
df.columns = df.columns.str.lower()

In [31]:
df.columns

Index(['category', 'message'], dtype='object')

In [32]:
df["spam"] = df["category"].apply(lambda x: 1 if x == "spam" else 0)

In [33]:
df.head()

category                                            message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [34]:
df.shape

(5572, 3)

In [35]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df["message"], df["spam"], test_size = 0.2, random_state = 42)

In [36]:
X_train

1978    Reply to win £100 weekly! Where will the 2006 ...
3989    Hello. Sort of out in town already. That . So ...
3935     How come guoyang go n tell her? Then u told her?
4078    Hey sathya till now we dint meet not even a si...
4086    Orange brings you ringtones from all time Char...
                              ...                        
3772    Hi, wlcome back, did wonder if you got eaten b...
5191                               Sorry, I'll call later
5226        Prabha..i'm soryda..realy..frm heart i'm sory
5390                           Nt joking seriously i told
860               Did he just say somebody is named tampa
Name: message, Length: 4457, dtype: object

In [37]:
X_test

3245    Squeeeeeze!! This is christmas hug.. If u lik ...
944     And also I've sorta blown him off a couple tim...
1044    Mmm thats better now i got a roast down me! i’...
2484        Mm have some kanji dont eat anything heavy ok
812     So there's a ring that comes with the guys cos...
                              ...                        
4264    Den only weekdays got special price... Haiz......
2439         I not busy juz dun wan 2 go so early.. Hee..
5556    Yes i have. So that's why u texted. Pshew...mi...
4205    How are you enjoying this semester? Take care ...
4293                                                G.W.R
Name: message, Length: 1115, dtype: object

In [38]:
y_train

1978    1
3989    0
3935    0
4078    0
4086    1
       ..
3772    0
5191    0
5226    0
5390    0
860     0
Name: spam, Length: 4457, dtype: int64

In [39]:
y_test

3245    0
944     0
1044    0
2484    0
812     0
       ..
4264    0
2439    0
5556    0
4205    0
4293    0
Name: spam, Length: 1115, dtype: int64

In [15]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59275 stored elements and shape (4457, 7701)>

In [40]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0], shape=(7701,))

In [41]:
X_train_cv.shape

(4457, 7701)

In [46]:
v.get_feature_names_out()[6847]

'tie'

In [47]:
v.vocabulary_

{'reply': 5687,
 'to': 6888,
 'win': 7474,
 '100': 258,
 'weekly': 7396,
 'where': 7437,
 'will': 7471,
 'the': 6773,
 '2006': 354,
 'fifa': 2805,
 'world': 7555,
 'cup': 2106,
 'be': 1271,
 'held': 3364,
 'send': 5980,
 'stop': 6460,
 '87239': 694,
 'end': 2568,
 'service': 5999,
 'hello': 3369,
 'sort': 6304,
 'of': 4854,
 'out': 4976,
 'in': 3603,
 'town': 6959,
 'already': 924,
 'that': 6770,
 'so': 6252,
 'dont': 2395,
 'rush': 5825,
 'home': 3441,
 'am': 934,
 'eating': 2504,
 'nachos': 4650,
 'let': 4057,
 'you': 7662,
 'know': 3926,
 'eta': 2627,
 'how': 3487,
 'come': 1902,
 'guoyang': 3258,
 'go': 3140,
 'tell': 6711,
 'her': 3384,
 'then': 6784,
 'told': 6904,
 'hey': 3392,
 'sathya': 5881,
 'till': 6856,
 'now': 4808,
 'we': 7372,
 'dint': 2323,
 'meet': 4392,
 'not': 4797,
 'even': 2638,
 'single': 6147,
 'time': 6857,
 'can': 1629,
 'saw': 5894,
 'situation': 6164,
 'orange': 4945,
 'brings': 1509,
 'ringtones': 5763,
 'from': 2993,
 'all': 911,
 'chart': 1733,
 'heroes':

In [48]:
def get_spam_number():
    if x == "spam":
        return 1
    return 0

In [51]:
X_train_np = X_train_cv.toarray()
X_train_np[:4][0]

array([0, 0, 0, ..., 0, 0, 0], shape=(7701,))

In [53]:
np.where(X_train_np[0]!=0)

(array([ 258,  354,  694, 1271, 2106, 2568, 2805, 3364, 5687, 5980, 5999,
        6460, 6773, 6888, 7396, 7437, 7471, 7474, 7555]),)

In [57]:
X_train[:4]

1978    Reply to win £100 weekly! Where will the 2006 ...
3989    Hello. Sort of out in town already. That . So ...
3935     How come guoyang go n tell her? Then u told her?
4078    Hey sathya till now we dint meet not even a si...
Name: message, dtype: object